version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - gosec
    - revive
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  gosec:
    excludes:
      - G104  # Errors unhandled (overlaps errcheck)
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - protos
    - docs
    - vendor
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - errcheck
